export { Adventages } from './adventages/Adventages'
export { DealsBlock } from './deals-of-day/index'
export { Footer } from './footer/index'
export { Header } from './header/index'
export { MainSlider } from './main-slider/index'
export { ShopBrands } from './shop-by-brands/index'
export { ShopCategoryBlock } from './shop-categories/index'
